"""Python problem bank for seed exercises."""
PROBLEMS = [
    # ── Strings ────────────────────────────────────────
    {"topic":"strings","diff":1,"title":"Reverse A String",
     "description":"Implement reverse_string(s) returning the string reversed.\n\nExample: reverse_string('abc') -> 'cba'.",
     "sample_data":"reverse_string('abc') -> 'cba'",
     "expected_output":"cba",
     "solution":"def reverse_string(s):\n    return s[::-1]",
     "tags":["py:string_manipulation"],"hints":["Use slicing.","s[start:stop:step].","s[::-1]"],
     "test_cases":[{"name":"basic","input":"reverse_string('abc')","expected":"'cba'"},{"name":"empty","input":"reverse_string('')","expected":"''"},{"name":"single","input":"reverse_string('a')","expected":"'a'"}]},
    {"topic":"strings","diff":1,"title":"Count Vowels",
     "description":"Implement count_vowels(s) returning the count of a,e,i,o,u (case-insensitive).",
     "sample_data":"count_vowels('hello') -> 2",
     "expected_output":"2",
     "solution":"def count_vowels(s):\n    return sum(1 for c in s.lower() if c in 'aeiou')",
     "tags":["py:string_manipulation"],"hints":["Lowercase first.","Iterate chars.","Sum 1 for c in 'aeiou'."],
     "test_cases":[{"name":"basic","input":"count_vowels('hello')","expected":"2"},{"name":"all","input":"count_vowels('AEIOU')","expected":"5"},{"name":"none","input":"count_vowels('xyz')","expected":"0"}]},
    {"topic":"strings","diff":2,"title":"Palindrome Check",
     "description":"Implement is_palindrome(s) (case-insensitive, ignore spaces).",
     "sample_data":"is_palindrome('Race car') -> True",
     "expected_output":"True",
     "solution":"def is_palindrome(s):\n    t = ''.join(c.lower() for c in s if not c.isspace())\n    return t == t[::-1]",
     "tags":["py:string_manipulation"],"hints":["Normalize first.","Lowercase + strip spaces.","Compare to reversed."],
     "test_cases":[{"name":"yes","input":"is_palindrome('racecar')","expected":"True"},{"name":"spaces","input":"is_palindrome('Race car')","expected":"True"},{"name":"no","input":"is_palindrome('hello')","expected":"False"}]},
    {"topic":"strings","diff":2,"title":"Anagram Check",
     "description":"Implement is_anagram(a,b) returning True if a and b are anagrams (ignore case and spaces).",
     "sample_data":"is_anagram('listen','silent') -> True",
     "expected_output":"True",
     "solution":"def is_anagram(a,b):\n    norm = lambda s: sorted(c.lower() for c in s if not c.isspace())\n    return norm(a) == norm(b)",
     "tags":["py:string_manipulation"],"hints":["Sort characters.","Strip spaces, lowercase.","sorted(...) == sorted(...)"],
     "test_cases":[{"name":"yes","input":"is_anagram('listen','silent')","expected":"True"},{"name":"no","input":"is_anagram('abc','abd')","expected":"False"}]},
    {"topic":"strings","diff":2,"title":"Most Common Character",
     "description":"Implement most_common_char(s) returning the most frequent character. Break ties by first appearance.",
     "sample_data":"most_common_char('aabbbcc') -> 'b'",
     "expected_output":"b",
     "solution":"def most_common_char(s):\n    from collections import Counter\n    c = Counter(s)\n    return max(s, key=lambda ch: c[ch]) if s else ''",
     "tags":["py:string_manipulation","py:collections"],"hints":["Use Counter.","Tie-break by first in string.","max(s, key=lambda ch: c[ch])"],
     "test_cases":[{"name":"basic","input":"most_common_char('aabbbcc')","expected":"'b'"},{"name":"single","input":"most_common_char('x')","expected":"'x'"}]},
    {"topic":"strings","diff":3,"title":"Run-Length Encode",
     "description":"Implement compress(s) returning RLE like 'aaabbc' -> 'a3b2c1'.",
     "sample_data":"compress('aaabbc') -> 'a3b2c1'",
     "expected_output":"a3b2c1",
     "solution":"def compress(s):\n    if not s: return ''\n    out, prev, cnt = [], s[0], 0\n    for c in s:\n        if c == prev: cnt += 1\n        else:\n            out.append(f'{prev}{cnt}'); prev=c; cnt=1\n    out.append(f'{prev}{cnt}')\n    return ''.join(out)",
     "tags":["py:string_manipulation"],"hints":["Iterate, track prev char.","Reset count on change.","Append final group."],
     "test_cases":[{"name":"basic","input":"compress('aaabbc')","expected":"'a3b2c1'"},{"name":"empty","input":"compress('')","expected":"''"},{"name":"single","input":"compress('a')","expected":"'a1'"}]},
    {"topic":"strings","diff":3,"title":"Longest Word",
     "description":"Implement longest_word(s) returning the longest space-separated word. Ties: return the first.",
     "sample_data":"longest_word('a bb ccc dd') -> 'ccc'",
     "expected_output":"ccc",
     "solution":"def longest_word(s):\n    return max(s.split(), key=len) if s.split() else ''",
     "tags":["py:string_manipulation"],"hints":["split() then max with key=len.","Handle empty.","max(s.split(), key=len)"],
     "test_cases":[{"name":"basic","input":"longest_word('a bb ccc dd')","expected":"'ccc'"},{"name":"empty","input":"longest_word('')","expected":"''"}]},

    # ── Lists & Comprehensions ─────────────────────────
    {"topic":"lists_comprehensions","diff":1,"title":"Sum Of Positives",
     "description":"Implement sum_positive(nums) summing only positive numbers.",
     "sample_data":"sum_positive([1,-2,3,-4]) -> 4",
     "expected_output":"4",
     "solution":"def sum_positive(nums):\n    return sum(n for n in nums if n>0)",
     "tags":["py:comprehensions"],"hints":["Generator + sum.","Filter n>0.","sum(n for n in nums if n>0)"],
     "test_cases":[{"name":"mixed","input":"sum_positive([1,-2,3,-4])","expected":"4"},{"name":"empty","input":"sum_positive([])","expected":"0"},{"name":"neg","input":"sum_positive([-1,-2])","expected":"0"}]},
    {"topic":"lists_comprehensions","diff":2,"title":"Second Largest",
     "description":"Implement second_largest(nums) returning the 2nd-largest distinct number. Return None if not possible.",
     "sample_data":"second_largest([1,2,3,3]) -> 2",
     "expected_output":"2",
     "solution":"def second_largest(nums):\n    u = sorted(set(nums), reverse=True)\n    return u[1] if len(u)>=2 else None",
     "tags":["py:data_structures","py:sorting"],"hints":["Dedupe with set.","Sort desc.","Index [1] if len>=2"],
     "test_cases":[{"name":"basic","input":"second_largest([1,2,3,3])","expected":"2"},{"name":"one","input":"second_largest([5])","expected":"None"},{"name":"dupes","input":"second_largest([2,2,2])","expected":"None"}]},
    {"topic":"lists_comprehensions","diff":2,"title":"Flatten One Level",
     "description":"Implement flatten1(xs) flattening a list of lists by exactly one level.",
     "sample_data":"flatten1([[1,2],[3]]) -> [1,2,3]",
     "expected_output":"[1, 2, 3]",
     "solution":"def flatten1(xs):\n    return [x for sub in xs for x in sub]",
     "tags":["py:comprehensions"],"hints":["Nested comprehension.","[x for sub in xs for x in sub].","One level only."],
     "test_cases":[{"name":"basic","input":"flatten1([[1,2],[3]])","expected":"[1, 2, 3]"},{"name":"empty","input":"flatten1([[]])","expected":"[]"}]},
    {"topic":"lists_comprehensions","diff":2,"title":"Unique Preserving Order",
     "description":"Implement unique(xs) removing duplicates while keeping first occurrence order.",
     "sample_data":"unique([1,2,1,3,2,4]) -> [1,2,3,4]",
     "expected_output":"[1, 2, 3, 4]",
     "solution":"def unique(xs):\n    seen=set(); out=[]\n    for x in xs:\n        if x not in seen: seen.add(x); out.append(x)\n    return out",
     "tags":["py:data_structures"],"hints":["Track a seen set.","Append if new.","Preserve order."],
     "test_cases":[{"name":"basic","input":"unique([1,2,1,3,2,4])","expected":"[1, 2, 3, 4]"},{"name":"empty","input":"unique([])","expected":"[]"}]},
    {"topic":"lists_comprehensions","diff":2,"title":"Running Maximum",
     "description":"Implement running_max(nums) returning a list where element i = max of nums[0..i].",
     "sample_data":"running_max([1,3,2,5,4]) -> [1,3,3,5,5]",
     "expected_output":"[1, 3, 3, 5, 5]",
     "solution":"def running_max(nums):\n    out=[]; m=float('-inf')\n    for n in nums:\n        m=max(m,n); out.append(m)\n    return out",
     "tags":["py:data_structures"],"hints":["Track current max.","Append after update.","max(m,n) each iter"],
     "test_cases":[{"name":"basic","input":"running_max([1,3,2,5,4])","expected":"[1, 3, 3, 5, 5]"},{"name":"empty","input":"running_max([])","expected":"[]"}]},
    {"topic":"lists_comprehensions","diff":3,"title":"Chunk Into Groups",
     "description":"Implement chunk(xs, n) splitting xs into sublists of size n (last may be shorter).",
     "sample_data":"chunk([1,2,3,4,5], 2) -> [[1,2],[3,4],[5]]",
     "expected_output":"[[1, 2], [3, 4], [5]]",
     "solution":"def chunk(xs, n):\n    return [xs[i:i+n] for i in range(0,len(xs),n)]",
     "tags":["py:comprehensions"],"hints":["Slice with step.","range(0,len,n).","xs[i:i+n]"],
     "test_cases":[{"name":"basic","input":"chunk([1,2,3,4,5],2)","expected":"[[1, 2], [3, 4], [5]]"},{"name":"exact","input":"chunk([1,2,3],3)","expected":"[[1, 2, 3]]"}]},

    # ── 2D Lists / Matrices ────────────────────────────
    {"topic":"matrices_2d","diff":2,"title":"Matrix Sum",
     "description":"Implement matrix_sum(m) returning the total sum of all elements in 2D list m.",
     "sample_data":"matrix_sum([[1,2],[3,4]]) -> 10",
     "expected_output":"10",
     "solution":"def matrix_sum(m):\n    return sum(sum(row) for row in m)",
     "tags":["py:data_structures"],"hints":["Nested sum.","sum(row) per row.","sum(sum(row) for row in m)"],
     "test_cases":[{"name":"basic","input":"matrix_sum([[1,2],[3,4]])","expected":"10"},{"name":"single","input":"matrix_sum([[5]])","expected":"5"}]},
    {"topic":"matrices_2d","diff":2,"title":"Max Per Row",
     "description":"Implement row_max(m) returning a list with the max of each row.",
     "sample_data":"row_max([[1,5,3],[2,2,2],[9,0,1]]) -> [5,2,9]",
     "expected_output":"[5, 2, 9]",
     "solution":"def row_max(m):\n    return [max(r) for r in m]",
     "tags":["py:data_structures","py:comprehensions"],"hints":["Comprehension.","max(row) each.","[max(r) for r in m]"],
     "test_cases":[{"name":"basic","input":"row_max([[1,5,3],[2,2,2],[9,0,1]])","expected":"[5, 2, 9]"}]},
    {"topic":"matrices_2d","diff":3,"title":"Transpose Matrix",
     "description":"Implement transpose(m) returning the transpose of a non-empty rectangular 2D list.",
     "sample_data":"transpose([[1,2,3],[4,5,6]]) -> [[1,4],[2,5],[3,6]]",
     "expected_output":"[[1, 4], [2, 5], [3, 6]]",
     "solution":"def transpose(m):\n    return [list(row) for row in zip(*m)]",
     "tags":["py:data_structures"],"hints":["zip(*m) swaps axes.","Wrap tuples in list.","[list(r) for r in zip(*m)]"],
     "test_cases":[{"name":"basic","input":"transpose([[1,2,3],[4,5,6]])","expected":"[[1, 4], [2, 5], [3, 6]]"},{"name":"single","input":"transpose([[1]])","expected":"[[1]]"}]},
    {"topic":"matrices_2d","diff":3,"title":"Rotate 90 Degrees Clockwise",
     "description":"Implement rotate90(m) rotating a square matrix clockwise 90 degrees.",
     "sample_data":"rotate90([[1,2],[3,4]]) -> [[3,1],[4,2]]",
     "expected_output":"[[3, 1], [4, 2]]",
     "solution":"def rotate90(m):\n    return [list(row) for row in zip(*m[::-1])]",
     "tags":["py:data_structures"],"hints":["Reverse rows then transpose.","zip(*m[::-1]).","Equivalent to clockwise rotation."],
     "test_cases":[{"name":"2x2","input":"rotate90([[1,2],[3,4]])","expected":"[[3, 1], [4, 2]]"},{"name":"3x3","input":"rotate90([[1,2,3],[4,5,6],[7,8,9]])","expected":"[[7, 4, 1], [8, 5, 2], [9, 6, 3]]"}]},
    {"topic":"matrices_2d","diff":4,"title":"Spiral Order Traversal",
     "description":"Implement spiral(m) returning elements in spiral order (top-row, right-col, bottom-row reversed, left-col upward).",
     "sample_data":"spiral([[1,2,3],[4,5,6],[7,8,9]]) -> [1,2,3,6,9,8,7,4,5]",
     "expected_output":"[1, 2, 3, 6, 9, 8, 7, 4, 5]",
     "solution":"def spiral(m):\n    res=[]; m=[row[:] for row in m]\n    while m:\n        res += m.pop(0)\n        if m and m[0]:\n            for r in m: res.append(r.pop())\n        if m:\n            res += m.pop()[::-1]\n        if m and m[0]:\n            for r in reversed(m): res.append(r.pop(0))\n    return res",
     "tags":["py:data_structures"],"hints":["Peel layers.","pop rows/cols in order.","Top, right, bottom, left."],
     "test_cases":[{"name":"3x3","input":"spiral([[1,2,3],[4,5,6],[7,8,9]])","expected":"[1, 2, 3, 6, 9, 8, 7, 4, 5]"},{"name":"2x2","input":"spiral([[1,2],[3,4]])","expected":"[1, 2, 4, 3]"}]},

    # ── Dicts & Sets ───────────────────────────────────
    {"topic":"dicts_sets","diff":2,"title":"Word Frequency",
     "description":"Implement word_freq(s) returning a dict mapping each lowercased word to its count.",
     "sample_data":"word_freq('the cat the dog') -> {'the':2,'cat':1,'dog':1}",
     "expected_output":"{'the': 2, 'cat': 1, 'dog': 1}",
     "solution":"def word_freq(s):\n    from collections import Counter\n    return dict(Counter(s.lower().split())) if s else {}",
     "tags":["py:data_structures","py:collections"],"hints":["Lowercase then split.","Counter then dict.","Counter(s.lower().split())"],
     "test_cases":[{"name":"basic","input":"word_freq('the cat the dog')","expected":"{'the': 2, 'cat': 1, 'dog': 1}"},{"name":"empty","input":"word_freq('')","expected":"{}"}]},
    {"topic":"dicts_sets","diff":2,"title":"List Intersection",
     "description":"Implement intersect(a,b) returning sorted list of values present in both (deduplicated).",
     "sample_data":"intersect([1,2,2,3],[2,3,4]) -> [2,3]",
     "expected_output":"[2, 3]",
     "solution":"def intersect(a,b):\n    return sorted(set(a) & set(b))",
     "tags":["py:data_structures"],"hints":["Use sets.","Intersection: &.","sorted(set(a)&set(b))"],
     "test_cases":[{"name":"basic","input":"intersect([1,2,2,3],[2,3,4])","expected":"[2, 3]"},{"name":"none","input":"intersect([],[1])","expected":"[]"}]},
    {"topic":"dicts_sets","diff":2,"title":"Invert Dict",
     "description":"Implement invert(d) swapping keys and values. Assume values are unique.",
     "sample_data":"invert({'a':1,'b':2}) -> {1:'a',2:'b'}",
     "expected_output":"{1: 'a', 2: 'b'}",
     "solution":"def invert(d):\n    return {v:k for k,v in d.items()}",
     "tags":["py:data_structures"],"hints":["Comprehension.","{v:k for k,v in d.items()}.","Values become keys."],
     "test_cases":[{"name":"basic","input":"invert({'a':1,'b':2})","expected":"{1: 'a', 2: 'b'}"},{"name":"empty","input":"invert({})","expected":"{}"}]},
    {"topic":"dicts_sets","diff":3,"title":"Two-Sum Indices",
     "description":"Implement two_sum(nums, target) returning a tuple (i,j) with i<j such that nums[i]+nums[j]==target, or None.",
     "sample_data":"two_sum([2,7,11,15], 9) -> (0,1)",
     "expected_output":"(0, 1)",
     "solution":"def two_sum(nums,target):\n    seen={}\n    for j,n in enumerate(nums):\n        if target-n in seen: return (seen[target-n], j)\n        seen[n]=j\n    return None",
     "tags":["py:data_structures","py:big_o"],"hints":["Hash complement to index.","One pass.","seen[target-n] -> i"],
     "test_cases":[{"name":"basic","input":"two_sum([2,7,11,15],9)","expected":"(0, 1)"},{"name":"dupes","input":"two_sum([3,3],6)","expected":"(0, 1)"},{"name":"none","input":"two_sum([1,2,3],10)","expected":"None"}]},
    {"topic":"dicts_sets","diff":3,"title":"First Non-Repeating Char",
     "description":"Implement first_unique(s) returning the first character that appears exactly once, or '' if none.",
     "sample_data":"first_unique('leetcode') -> 'l'",
     "expected_output":"l",
     "solution":"def first_unique(s):\n    from collections import Counter\n    c=Counter(s)\n    for ch in s:\n        if c[ch]==1: return ch\n    return ''",
     "tags":["py:data_structures","py:collections"],"hints":["Count chars.","Scan in order.","First with count 1."],
     "test_cases":[{"name":"basic","input":"first_unique('leetcode')","expected":"'l'"},{"name":"none","input":"first_unique('aabbcc')","expected":"''"}]},
    {"topic":"dicts_sets","diff":3,"title":"Group Words By Length",
     "description":"Implement group_by_len(words) returning a dict {length: sorted list of words}.",
     "sample_data":"group_by_len(['bat','car','apple','ant']) -> {3:['ant','bat','car'],5:['apple']}",
     "expected_output":"{3: ['ant', 'bat', 'car'], 5: ['apple']}",
     "solution":"def group_by_len(words):\n    from collections import defaultdict\n    d=defaultdict(list)\n    for w in words: d[len(w)].append(w)\n    return {k:sorted(v) for k,v in d.items()}",
     "tags":["py:data_structures","py:collections"],"hints":["defaultdict(list).","Group on len(w).","Sort each list."],
     "test_cases":[{"name":"basic","input":"group_by_len(['bat','car','apple','ant'])","expected":"{3: ['ant', 'bat', 'car'], 5: ['apple']}"}]},
    {"topic":"dicts_sets","diff":4,"title":"Group Anagrams",
     "description":"Implement group_anagrams(words) returning a list of groups; each group sorted; whole result sorted by first word.",
     "sample_data":"group_anagrams(['eat','tea','tan','ate','nat','bat'])",
     "expected_output":"[['bat'], ['ate', 'eat', 'tea'], ['nat', 'tan']]",
     "solution":"def group_anagrams(words):\n    from collections import defaultdict\n    d=defaultdict(list)\n    for w in words: d[''.join(sorted(w))].append(w)\n    groups=[sorted(g) for g in d.values()]\n    groups.sort(key=lambda g:g[0])\n    return groups",
     "tags":["py:data_structures","py:collections","py:sorting"],"hints":["Sorted letters = key.","defaultdict(list).","Sort each group then list."],
     "test_cases":[{"name":"basic","input":"group_anagrams(['eat','tea','tan','ate','nat','bat'])","expected":"[['bat'], ['ate', 'eat', 'tea'], ['nat', 'tan']]"}]},

    # ── Sorting & Ranking ──────────────────────────────
    {"topic":"sorting_ranking","diff":2,"title":"Sort Strings By Length",
     "description":"Implement sort_by_len(words) returning words sorted by length ascending, ties alphabetical.",
     "sample_data":"sort_by_len(['bb','a','ccc','ab']) -> ['a','ab','bb','ccc']",
     "expected_output":"['a', 'ab', 'bb', 'ccc']",
     "solution":"def sort_by_len(words):\n    return sorted(words, key=lambda w:(len(w), w))",
     "tags":["py:sorting"],"hints":["sorted with tuple key.","(len(w), w) for tie-break.","key=lambda w:(len(w),w)"],
     "test_cases":[{"name":"basic","input":"sort_by_len(['bb','a','ccc','ab'])","expected":"['a', 'ab', 'bb', 'ccc']"}]},
    {"topic":"sorting_ranking","diff":3,"title":"Dense Rank Scores",
     "description":"Implement dense_rank(scores) returning a list of dense ranks (1=highest). Same score same rank, no gaps.",
     "sample_data":"dense_rank([100,50,50,40]) -> [1,2,2,3]",
     "expected_output":"[1, 2, 2, 3]",
     "solution":"def dense_rank(scores):\n    uniq=sorted(set(scores), reverse=True)\n    pos={v:i+1 for i,v in enumerate(uniq)}\n    return [pos[s] for s in scores]",
     "tags":["py:sorting"],"hints":["Map score to dense rank.","Sort distinct desc.","Lookup in dict."],
     "test_cases":[{"name":"basic","input":"dense_rank([100,50,50,40])","expected":"[1, 2, 2, 3]"},{"name":"single","input":"dense_rank([10])","expected":"[1]"}]},
    {"topic":"sorting_ranking","diff":3,"title":"Sort Records By Age",
     "description":"Implement sort_records(rs) sorting list of dicts by 'age' asc then 'name' asc.",
     "sample_data":"sort_records([{'name':'B','age':30},{'name':'A','age':30},{'name':'C','age':25}])",
     "expected_output":"[{'name': 'C', 'age': 25}, {'name': 'A', 'age': 30}, {'name': 'B', 'age': 30}]",
     "solution":"def sort_records(rs):\n    return sorted(rs, key=lambda r:(r['age'], r['name']))",
     "tags":["py:sorting"],"hints":["Tuple key.","(age, name).","sorted with key"],
     "test_cases":[{"name":"basic","input":"sort_records([{'name':'B','age':30},{'name':'A','age':30},{'name':'C','age':25}])","expected":"[{'name': 'C', 'age': 25}, {'name': 'A', 'age': 30}, {'name': 'B', 'age': 30}]"}]},
    {"topic":"sorting_ranking","diff":3,"title":"Merge Two Sorted Lists",
     "description":"Implement merge(a,b) merging two sorted lists into one sorted list in O(n+m) without sorted().",
     "sample_data":"merge([1,3,5],[2,4,6]) -> [1,2,3,4,5,6]",
     "expected_output":"[1, 2, 3, 4, 5, 6]",
     "solution":"def merge(a,b):\n    i=j=0; out=[]\n    while i<len(a) and j<len(b):\n        if a[i]<=b[j]: out.append(a[i]); i+=1\n        else: out.append(b[j]); j+=1\n    out.extend(a[i:]); out.extend(b[j:])\n    return out",
     "tags":["py:sorting","py:data_structures"],"hints":["Two pointers.","Compare heads.","Extend remainder at end."],
     "test_cases":[{"name":"basic","input":"merge([1,3,5],[2,4,6])","expected":"[1, 2, 3, 4, 5, 6]"},{"name":"empty","input":"merge([],[1,2])","expected":"[1, 2]"}]},
    {"topic":"sorting_ranking","diff":4,"title":"Top K Frequent",
     "description":"Implement top_k(nums, k) returning the k most frequent numbers, sorted by frequency desc then value asc.",
     "sample_data":"top_k([1,1,1,2,2,3], 2) -> [1,2]",
     "expected_output":"[1, 2]",
     "solution":"def top_k(nums, k):\n    from collections import Counter\n    c=Counter(nums)\n    return [n for n,_ in sorted(c.items(), key=lambda kv:(-kv[1], kv[0]))[:k]]",
     "tags":["py:sorting","py:collections"],"hints":["Counter.","Sort by (-count, value).","Slice [:k]"],
     "test_cases":[{"name":"basic","input":"top_k([1,1,1,2,2,3],2)","expected":"[1, 2]"},{"name":"one","input":"top_k([4,4,5],1)","expected":"[4]"}]},

    # ── Loops & Control Flow ───────────────────────────
    {"topic":"loops_control_flow","diff":1,"title":"FizzBuzz Up To N",
     "description":"Implement fb(n) returning list 1..n: 'Fizz' on 3, 'Buzz' on 5, 'FizzBuzz' on both, else str(i).",
     "sample_data":"fb(5) -> ['1','2','Fizz','4','Buzz']",
     "expected_output":"['1', '2', 'Fizz', '4', 'Buzz']",
     "solution":"def fb(n):\n    out=[]\n    for i in range(1,n+1):\n        if i%15==0: out.append('FizzBuzz')\n        elif i%3==0: out.append('Fizz')\n        elif i%5==0: out.append('Buzz')\n        else: out.append(str(i))\n    return out",
     "tags":["py:data_structures"],"hints":["Check 15 first.","Then 3, 5.","Else str(i)"],
     "test_cases":[{"name":"basic","input":"fb(5)","expected":"['1', '2', 'Fizz', '4', 'Buzz']"},{"name":"zero","input":"fb(0)","expected":"[]"}]},
    {"topic":"loops_control_flow","diff":1,"title":"Factorial",
     "description":"Implement factorial(n) for n>=0 iteratively.",
     "sample_data":"factorial(5) -> 120",
     "expected_output":"120",
     "solution":"def factorial(n):\n    r=1\n    for i in range(2,n+1): r*=i\n    return r",
     "tags":["py:data_structures"],"hints":["Accumulator = 1.","Multiply 2..n.","range(2,n+1)"],
     "test_cases":[{"name":"zero","input":"factorial(0)","expected":"1"},{"name":"five","input":"factorial(5)","expected":"120"}]},
    {"topic":"loops_control_flow","diff":2,"title":"Is Prime",
     "description":"Implement is_prime(n) returning True if n is a prime > 1.",
     "sample_data":"is_prime(17) -> True",
     "expected_output":"True",
     "solution":"def is_prime(n):\n    if n<2: return False\n    if n<4: return True\n    if n%2==0: return False\n    i=3\n    while i*i<=n:\n        if n%i==0: return False\n        i+=2\n    return True",
     "tags":["py:data_structures"],"hints":["Trial division.","Up to sqrt(n).","Skip evens after 2."],
     "test_cases":[{"name":"yes","input":"is_prime(17)","expected":"True"},{"name":"no","input":"is_prime(4)","expected":"False"},{"name":"one","input":"is_prime(1)","expected":"False"}]},
    {"topic":"loops_control_flow","diff":1,"title":"Count Down By Step",
     "description":"Implement countdown(start, step) returning list from start down to 0 inclusive by step.",
     "sample_data":"countdown(10,3) -> [10,7,4,1]",
     "expected_output":"[10, 7, 4, 1]",
     "solution":"def countdown(start, step):\n    out=[]; n=start\n    while n>=0:\n        out.append(n); n-=step\n    return out",
     "tags":["py:data_structures"],"hints":["While n>=0.","Append then decrement.","Stop when next would go negative."],
     "test_cases":[{"name":"basic","input":"countdown(10,3)","expected":"[10, 7, 4, 1]"},{"name":"zero","input":"countdown(0,1)","expected":"[0]"}]},

    # ── Recursion ──────────────────────────────────────
    {"topic":"recursion","diff":2,"title":"Fibonacci Iterative",
     "description":"Implement fib(n) with n>=0. fib(0)=0, fib(1)=1.",
     "sample_data":"fib(10) -> 55",
     "expected_output":"55",
     "solution":"def fib(n):\n    a,b=0,1\n    for _ in range(n): a,b=b,a+b\n    return a",
     "tags":["py:data_structures"],"hints":["fib(0)=0, fib(1)=1.","Iterate (a,b)=(b,a+b).","Avoid naive O(2^n)."],
     "test_cases":[{"name":"zero","input":"fib(0)","expected":"0"},{"name":"ten","input":"fib(10)","expected":"55"}]},
    {"topic":"recursion","diff":2,"title":"Recursive Sum",
     "description":"Implement rsum(xs) recursively summing a list.",
     "sample_data":"rsum([1,2,3]) -> 6",
     "expected_output":"6",
     "solution":"def rsum(xs):\n    if not xs: return 0\n    return xs[0] + rsum(xs[1:])",
     "tags":["py:data_structures"],"hints":["Base: empty.","Recursive: head + rsum(rest).","xs[0] + rsum(xs[1:])"],
     "test_cases":[{"name":"basic","input":"rsum([1,2,3])","expected":"6"},{"name":"empty","input":"rsum([])","expected":"0"}]},
    {"topic":"recursion","diff":3,"title":"Fast Power",
     "description":"Implement power(x, n) for integer n>=0 in O(log n) using exponentiation by squaring.",
     "sample_data":"power(2,10) -> 1024",
     "expected_output":"1024",
     "solution":"def power(x, n):\n    if n==0: return 1\n    half=power(x, n//2)\n    return half*half*(x if n%2 else 1)",
     "tags":["py:data_structures","py:big_o"],"hints":["Halve n each call.","Square the half.","Multiply by x if odd."],
     "test_cases":[{"name":"basic","input":"power(2,10)","expected":"1024"},{"name":"zero","input":"power(3,0)","expected":"1"}]},
    {"topic":"recursion","diff":4,"title":"Deep Flatten",
     "description":"Implement deep_flatten(xs) flattening arbitrarily nested lists to a single flat list.",
     "sample_data":"deep_flatten([1,[2,[3,4]],5]) -> [1,2,3,4,5]",
     "expected_output":"[1, 2, 3, 4, 5]",
     "solution":"def deep_flatten(xs):\n    out=[]\n    for x in xs:\n        if isinstance(x,list): out.extend(deep_flatten(x))\n        else: out.append(x)\n    return out",
     "tags":["py:data_structures"],"hints":["Recurse on list elements.","extend vs append.","isinstance(x,list)"],
     "test_cases":[{"name":"basic","input":"deep_flatten([1,[2,[3,4]],5])","expected":"[1, 2, 3, 4, 5]"},{"name":"deep","input":"deep_flatten([[[[1]]]])","expected":"[1]"}]},

    # ── Data Structures ────────────────────────────────
    {"topic":"data_structures","diff":3,"title":"Balanced Parentheses",
     "description":"Implement balanced(s) using a stack: True if every (, [, { has a matching closer in the right order.",
     "sample_data":"balanced('()[]{}') -> True",
     "expected_output":"True",
     "solution":"def balanced(s):\n    pairs={')':'(',']':'[','}':'{'}\n    st=[]\n    for c in s:\n        if c in '([{': st.append(c)\n        elif c in pairs:\n            if not st or st.pop()!=pairs[c]: return False\n    return not st",
     "tags":["py:custom_data_structures"],"hints":["Push openers.","Pop on closer.","Empty at end."],
     "test_cases":[{"name":"yes","input":"balanced('()[]{}')","expected":"True"},{"name":"no","input":"balanced('([)]')","expected":"False"},{"name":"open","input":"balanced('((')","expected":"False"}]},
    {"topic":"data_structures","diff":4,"title":"K Smallest Elements",
     "description":"Implement k_smallest(nums,k) returning the k smallest in ascending order using heapq.",
     "sample_data":"k_smallest([3,1,5,2,4],3) -> [1,2,3]",
     "expected_output":"[1, 2, 3]",
     "solution":"def k_smallest(nums,k):\n    import heapq\n    return sorted(heapq.nsmallest(k,nums))",
     "tags":["py:custom_data_structures"],"hints":["heapq.nsmallest.","Then sort.","Built-in is fine."],
     "test_cases":[{"name":"basic","input":"k_smallest([3,1,5,2,4],3)","expected":"[1, 2, 3]"},{"name":"one","input":"k_smallest([7],1)","expected":"[7]"}]},

    # ── Algorithms ─────────────────────────────────────
    {"topic":"algorithms","diff":3,"title":"Binary Search Index",
     "description":"Implement bsearch(arr, target) returning index of target in sorted arr, or -1.",
     "sample_data":"bsearch([1,3,5,7,9],5) -> 2",
     "expected_output":"2",
     "solution":"def bsearch(arr, target):\n    lo,hi=0,len(arr)-1\n    while lo<=hi:\n        mid=(lo+hi)//2\n        if arr[mid]==target: return mid\n        if arr[mid]<target: lo=mid+1\n        else: hi=mid-1\n    return -1",
     "tags":["py:big_o","py:data_structures"],"hints":["lo, hi pointers.","mid=(lo+hi)//2.","Adjust based on comparison."],
     "test_cases":[{"name":"found","input":"bsearch([1,3,5,7,9],5)","expected":"2"},{"name":"miss","input":"bsearch([1,2,3],4)","expected":"-1"}]},
    {"topic":"algorithms","diff":3,"title":"Pair Sum In Sorted",
     "description":"Implement pair_sum(arr, target) for SORTED arr. Return (i,j) with i<j where arr[i]+arr[j]==target, or None.",
     "sample_data":"pair_sum([1,2,4,7],6) -> (1,2)",
     "expected_output":"(1, 2)",
     "solution":"def pair_sum(arr, target):\n    i,j=0,len(arr)-1\n    while i<j:\n        s=arr[i]+arr[j]\n        if s==target: return (i,j)\n        if s<target: i+=1\n        else: j-=1\n    return None",
     "tags":["py:big_o","py:data_structures"],"hints":["Pointers at ends.","Move inward by sum vs target.","O(n)"],
     "test_cases":[{"name":"basic","input":"pair_sum([1,2,4,7],6)","expected":"(1, 2)"},{"name":"none","input":"pair_sum([1,2,3],10)","expected":"None"}]},
    {"topic":"algorithms","diff":4,"title":"Max Average Subarray K",
     "description":"Implement max_avg(arr,k) returning the max average of any contiguous subarray of length k.",
     "sample_data":"max_avg([1,12,-5,-6,50,3],4) -> 12.75",
     "expected_output":"12.75",
     "solution":"def max_avg(arr,k):\n    cur=sum(arr[:k]); best=cur\n    for i in range(k,len(arr)):\n        cur += arr[i]-arr[i-k]\n        if cur>best: best=cur\n    return best/k",
     "tags":["py:big_o","py:data_structures"],"hints":["Sliding window sum.","Slide: +new -old.","Divide by k at end."],
     "test_cases":[{"name":"basic","input":"max_avg([1,12,-5,-6,50,3],4)","expected":"12.75"},{"name":"single","input":"max_avg([5],1)","expected":"5.0"}]},
    {"topic":"algorithms","diff":4,"title":"Merge Intervals",
     "description":"Implement merge_intervals(ivs) merging overlapping [start,end] intervals; return sorted list.",
     "sample_data":"merge_intervals([[1,3],[2,6],[8,10],[15,18]]) -> [[1,6],[8,10],[15,18]]",
     "expected_output":"[[1, 6], [8, 10], [15, 18]]",
     "solution":"def merge_intervals(ivs):\n    ivs=sorted(ivs)\n    out=[]\n    for s,e in ivs:\n        if out and s<=out[-1][1]:\n            out[-1][1]=max(out[-1][1],e)\n        else:\n            out.append([s,e])\n    return out",
     "tags":["py:data_structures","py:sorting"],"hints":["Sort by start.","Merge if overlap.","Modify last in-place."],
     "test_cases":[{"name":"basic","input":"merge_intervals([[1,3],[2,6],[8,10],[15,18]])","expected":"[[1, 6], [8, 10], [15, 18]]"},{"name":"touch","input":"merge_intervals([[1,4],[4,5]])","expected":"[[1, 5]]"}]},

    # ── Big-O ──────────────────────────────────────────
    {"topic":"big_o","diff":2,"title":"O(n) Has Duplicate",
     "description":"Implement has_duplicate(nums) returning True if any value repeats. Must be O(n).",
     "sample_data":"has_duplicate([1,2,3]) -> False",
     "expected_output":"False",
     "solution":"def has_duplicate(nums):\n    return len(set(nums)) != len(nums)",
     "tags":["py:big_o"],"hints":["Use a set.","Compare sizes.","O(n) vs O(n^2)."],
     "test_cases":[{"name":"no","input":"has_duplicate([1,2,3])","expected":"False"},{"name":"yes","input":"has_duplicate([1,1])","expected":"True"}]},
    {"topic":"big_o","diff":3,"title":"Count Pairs Summing To K",
     "description":"Implement count_pairs(nums,k) counting unordered pairs (i<j) with nums[i]+nums[j]==k. O(n).",
     "sample_data":"count_pairs([1,5,7,-1,5],6) -> 3",
     "expected_output":"3",
     "solution":"def count_pairs(nums,k):\n    from collections import Counter\n    seen=Counter(); n=0\n    for x in nums:\n        n += seen[k-x]\n        seen[x]+=1\n    return n",
     "tags":["py:big_o","py:collections"],"hints":["For each x, look up k-x in seen.","Add count.","Then add x to seen."],
     "test_cases":[{"name":"basic","input":"count_pairs([1,5,7,-1,5],6)","expected":"3"}]},
    {"topic":"big_o","diff":3,"title":"O(n) Anagram Check",
     "description":"Implement anagram_n(a,b) in O(n) without sorting (use a counter).",
     "sample_data":"anagram_n('abc','cab') -> True",
     "expected_output":"True",
     "solution":"def anagram_n(a,b):\n    if len(a)!=len(b): return False\n    from collections import Counter\n    return Counter(a)==Counter(b)",
     "tags":["py:big_o"],"hints":["Lengths must match.","Counter equality.","O(n) vs sort O(n log n)."],
     "test_cases":[{"name":"yes","input":"anagram_n('abc','cab')","expected":"True"},{"name":"no","input":"anagram_n('abc','abd')","expected":"False"}]},
    {"topic":"big_o","diff":3,"title":"O(n+m) Common Element",
     "description":"Implement common(a,b) returning True if any value of a appears in b. Must be O(n+m).",
     "sample_data":"common([1,2,3],[4,2]) -> True",
     "expected_output":"True",
     "solution":"def common(a,b):\n    sb=set(b)\n    for x in a:\n        if x in sb: return True\n    return False",
     "tags":["py:big_o"],"hints":["Convert b to set.","Membership in set O(1).","Total O(n+m)"],
     "test_cases":[{"name":"yes","input":"common([1,2,3],[4,2])","expected":"True"},{"name":"no","input":"common([1],[2,3])","expected":"False"}]},

    # ── Scenario / ETL ─────────────────────────────────
    {"topic":"scenario_etl","diff":2,"title":"Clean Whitespace And Empties",
     "description":"Implement clean(values) taking list of strings: strip whitespace and drop empty/None values.",
     "sample_data":"clean(['  a ',' ','b',None,'',' c']) -> ['a','b','c']",
     "expected_output":"['a', 'b', 'c']",
     "solution":"def clean(values):\n    out=[]\n    for v in values:\n        if v is None: continue\n        s=v.strip()\n        if s: out.append(s)\n    return out",
     "tags":["py:data_structures","py:edge_case_hardening"],"hints":["Strip each.","Skip empty after strip.","Skip None."],
     "test_cases":[{"name":"basic","input":"clean(['  a ',' ','b',None,'',' c'])","expected":"['a', 'b', 'c']"}]},
    {"topic":"scenario_etl","diff":3,"title":"Parse Naive CSV",
     "description":"Implement parse_csv(text) where text has lines separated by newline, fields by comma. First line = header. Return list of dicts.",
     "sample_data":"parse_csv('name,age\\nAlice,30\\nBob,25')",
     "expected_output":"[{'name': 'Alice', 'age': '30'}, {'name': 'Bob', 'age': '25'}]",
     "solution":"def parse_csv(text):\n    if not text: return []\n    lines=text.split('\\n')\n    head=lines[0].split(',')\n    return [dict(zip(head, l.split(','))) for l in lines[1:] if l]",
     "tags":["py:data_structures","py:edge_case_hardening"],"hints":["Split by newline.","First line = header.","zip(head, row)"],
     "test_cases":[{"name":"basic","input":"parse_csv('name,age\\nAlice,30\\nBob,25')","expected":"[{'name': 'Alice', 'age': '30'}, {'name': 'Bob', 'age': '25'}]"},{"name":"empty","input":"parse_csv('')","expected":"[]"}]},
    {"topic":"scenario_etl","diff":3,"title":"Dedupe Records By Key",
     "description":"Implement dedupe(records, key) keeping the FIRST record for each value of records[i][key].",
     "sample_data":"dedupe([{'id':1,'v':'a'},{'id':2,'v':'b'},{'id':1,'v':'c'}],'id')",
     "expected_output":"[{'id': 1, 'v': 'a'}, {'id': 2, 'v': 'b'}]",
     "solution":"def dedupe(records, key):\n    seen=set(); out=[]\n    for r in records:\n        k=r[key]\n        if k not in seen: seen.add(k); out.append(r)\n    return out",
     "tags":["py:data_structures","py:edge_case_hardening"],"hints":["Track seen keys.","Skip duplicates.","Preserve order."],
     "test_cases":[{"name":"basic","input":"dedupe([{'id':1,'v':'a'},{'id':2,'v':'b'},{'id':1,'v':'c'}],'id')","expected":"[{'id': 1, 'v': 'a'}, {'id': 2, 'v': 'b'}]"}]},
    {"topic":"scenario_etl","diff":3,"title":"Aggregate Sales By Region",
     "description":"Given list of dicts {region, amount}, implement total_by_region(rows) returning dict {region: total}.",
     "sample_data":"total_by_region([{'region':'NA','amount':10},{'region':'EU','amount':5},{'region':'NA','amount':3}])",
     "expected_output":"{'NA': 13, 'EU': 5}",
     "solution":"def total_by_region(rows):\n    out={}\n    for r in rows: out[r['region']] = out.get(r['region'],0) + r['amount']\n    return out",
     "tags":["py:data_structures","py:edge_case_hardening"],"hints":["dict.get with default.","Accumulate per key.","One pass."],
     "test_cases":[{"name":"basic","input":"total_by_region([{'region':'NA','amount':10},{'region':'EU','amount':5},{'region':'NA','amount':3}])","expected":"{'NA': 13, 'EU': 5}"}]},
    {"topic":"scenario_etl","diff":4,"title":"Validate Records Against Schema",
     "description":"Implement validate(records) returning a list of bools: each record must have integer 'a' and string 'b'.",
     "sample_data":"validate([{'a':1,'b':'x'},{'a':'oops','b':'x'},{'a':2}])",
     "expected_output":"[True, False, False]",
     "solution":"def validate(records):\n    return [isinstance(r.get('a'),int) and isinstance(r.get('b'),str) for r in records]",
     "tags":["py:data_structures","py:edge_case_hardening"],"hints":["Loop records.","Check each field.","isinstance(r[f], t)"],
     "test_cases":[{"name":"basic","input":"validate([{'a':1,'b':'x'},{'a':'oops','b':'x'},{'a':2}])","expected":"[True, False, False]"}]},
    {"topic":"scenario_etl","diff":4,"title":"Pivot Long To Wide",
     "description":"Given rows {date, metric, value}, implement pivot(rows, metrics) returning one dict per date with metric columns. Missing = 0. Sort by date.",
     "sample_data":"pivot([{'date':'2024-01-01','metric':'clicks','value':10},{'date':'2024-01-01','metric':'views','value':100},{'date':'2024-01-02','metric':'clicks','value':5}],['clicks','views'])",
     "expected_output":"[{'date': '2024-01-01', 'clicks': 10, 'views': 100}, {'date': '2024-01-02', 'clicks': 5, 'views': 0}]",
     "solution":"def pivot(rows, metrics):\n    by_date={}\n    for r in rows:\n        d=by_date.setdefault(r['date'], {'date':r['date']})\n        d[r['metric']] = d.get(r['metric'],0) + r['value']\n    out=[]\n    for d in sorted(by_date):\n        rec={'date':d}\n        for m in metrics: rec[m] = by_date[d].get(m, 0)\n        out.append(rec)\n    return out",
     "tags":["py:data_structures","py:edge_case_hardening"],"hints":["Group by date.","Sum metrics.","Fill missing with 0."],
     "test_cases":[{"name":"basic","input":"pivot([{'date':'2024-01-01','metric':'clicks','value':10},{'date':'2024-01-01','metric':'views','value':100},{'date':'2024-01-02','metric':'clicks','value':5}],['clicks','views'])","expected":"[{'date': '2024-01-01', 'clicks': 10, 'views': 100}, {'date': '2024-01-02', 'clicks': 5, 'views': 0}]"}]},
]
