"""SQL problem bank for seed exercises."""
PROBLEMS = [
    # ── SELECT / WHERE / Filtering ─────────────────────
    {"topic":"select_filtering","diff":1,"title":"List Active Users",
     "description":"Return id and name of every active user, ordered by id.\n\nSQLite stores booleans as 0/1.",
     "sample_data":"CREATE TABLE users(id INT,name TEXT,is_active BOOLEAN);\nINSERT INTO users VALUES(1,'Alice',1),(2,'Bob',0),(3,'Carol',1),(4,'Dan',1);",
     "expected_output":"1|Alice\n3|Carol\n4|Dan",
     "solution":"SELECT id, name FROM users WHERE is_active = 1 ORDER BY id;",
     "tags":["sql:filtering"],"hints":["Filter with WHERE.","SQLite stores booleans as 0/1.","SELECT id, name FROM users WHERE is_active = 1 ORDER BY id;"]},
    {"topic":"select_filtering","diff":1,"title":"Products In Price Range",
     "description":"Return name of products priced between 10 and 50 inclusive, ordered alphabetically.",
     "sample_data":"CREATE TABLE products(id INT,name TEXT,price REAL);\nINSERT INTO products VALUES(1,'Pen',5),(2,'Book',12),(3,'Lamp',45),(4,'Desk',120),(5,'Mug',10);",
     "expected_output":"Book\nLamp\nMug",
     "solution":"SELECT name FROM products WHERE price BETWEEN 10 AND 50 ORDER BY name;",
     "tags":["sql:filtering"],"hints":["Use BETWEEN.","Inclusive bounds.","WHERE price BETWEEN 10 AND 50"]},
    {"topic":"select_filtering","diff":1,"title":"Users In Selected Cities",
     "description":"Return id, name of users in Paris or Lyon, ordered by id.",
     "sample_data":"CREATE TABLE users(id INT,name TEXT,city TEXT);\nINSERT INTO users VALUES(1,'A','Paris'),(2,'B','Berlin'),(3,'C','Lyon'),(4,'D','Paris');",
     "expected_output":"1|A\n3|C\n4|D",
     "solution":"SELECT id, name FROM users WHERE city IN ('Paris','Lyon') ORDER BY id;",
     "tags":["sql:filtering"],"hints":["Use IN(...).","List both cities.","WHERE city IN ('Paris','Lyon')"]},
    {"topic":"select_filtering","diff":2,"title":"Names Starting With A",
     "description":"Return name of employees whose name starts with A, sorted A-Z.",
     "sample_data":"CREATE TABLE employees(id INT,name TEXT);\nINSERT INTO employees VALUES(1,'Alice'),(2,'Adam'),(3,'Bob'),(4,'Anna'),(5,'Carl');",
     "expected_output":"Adam\nAlice\nAnna",
     "solution":"SELECT name FROM employees WHERE name LIKE 'A%' ORDER BY name;",
     "tags":["sql:filtering"],"hints":["LIKE with %.","A% matches anything starting with A.","WHERE name LIKE 'A%'"]},
    {"topic":"select_filtering","diff":2,"title":"Users Without Email",
     "description":"Return id and name of users with a NULL email.",
     "sample_data":"CREATE TABLE users(id INT,name TEXT,email TEXT);\nINSERT INTO users VALUES(1,'A','a@x.com'),(2,'B',NULL),(3,'C',NULL),(4,'D','d@x.com');",
     "expected_output":"2|B\n3|C",
     "solution":"SELECT id, name FROM users WHERE email IS NULL ORDER BY id;",
     "tags":["sql:filtering","sql:null_semantics"],"hints":["Use IS NULL.","Never = NULL.","WHERE email IS NULL"]},
    {"topic":"select_filtering","diff":2,"title":"Non-Cancelled Orders",
     "description":"Return order_id of orders whose status is anything except cancelled, ordered by id.",
     "sample_data":"CREATE TABLE orders(order_id INT,status TEXT);\nINSERT INTO orders VALUES(1,'paid'),(2,'cancelled'),(3,'pending'),(4,'paid');",
     "expected_output":"1\n3\n4",
     "solution":"SELECT order_id FROM orders WHERE status <> 'cancelled' ORDER BY order_id;",
     "tags":["sql:filtering"],"hints":["Use <> or !=.","Filter out cancelled.","WHERE status <> 'cancelled'"]},

    # ── ORDER BY / LIMIT / DISTINCT ────────────────────
    {"topic":"order_limit_distinct","diff":1,"title":"Top 3 Most Expensive",
     "description":"Return name, price of the 3 most expensive products, highest first.",
     "sample_data":"CREATE TABLE products(id INT,name TEXT,price REAL);\nINSERT INTO products VALUES(1,'A',5),(2,'B',12),(3,'C',45),(4,'D',120),(5,'E',80);",
     "expected_output":"D|120.0\nE|80.0\nC|45.0",
     "solution":"SELECT name, price FROM products ORDER BY price DESC LIMIT 3;",
     "tags":["sql:filtering"],"hints":["ORDER BY price DESC.","LIMIT 3.","ORDER BY price DESC LIMIT 3"]},
    {"topic":"order_limit_distinct","diff":1,"title":"Distinct Countries",
     "description":"Return each distinct country in alphabetical order.",
     "sample_data":"CREATE TABLE customers(id INT,country TEXT);\nINSERT INTO customers VALUES(1,'US'),(2,'DE'),(3,'US'),(4,'FR'),(5,'DE');",
     "expected_output":"DE\nFR\nUS",
     "solution":"SELECT DISTINCT country FROM customers ORDER BY country;",
     "tags":["sql:filtering"],"hints":["DISTINCT removes duplicates.","Sort A-Z.","SELECT DISTINCT country ... ORDER BY country"]},
    {"topic":"order_limit_distinct","diff":2,"title":"Sort By Two Columns",
     "description":"Return all rows ordered by department asc, then salary desc.",
     "sample_data":"CREATE TABLE emp(id INT,department TEXT,salary INT);\nINSERT INTO emp VALUES(1,'Eng',100),(2,'Sales',90),(3,'Eng',120),(4,'Sales',80);",
     "expected_output":"3|Eng|120\n1|Eng|100\n2|Sales|90\n4|Sales|80",
     "solution":"SELECT id, department, salary FROM emp ORDER BY department ASC, salary DESC;",
     "tags":["sql:filtering"],"hints":["Two sort keys.","ASC then DESC.","ORDER BY department, salary DESC"]},
    {"topic":"order_limit_distinct","diff":3,"title":"Second Highest Salary",
     "description":"Return the second-highest distinct salary as second_highest. If none, return NULL.",
     "sample_data":"CREATE TABLE emp(id INT,salary INT);\nINSERT INTO emp VALUES(1,100),(2,200),(3,200),(4,150);",
     "expected_output":"150",
     "solution":"SELECT MAX(salary) AS second_highest FROM emp WHERE salary < (SELECT MAX(salary) FROM emp);",
     "tags":["sql:filtering","sql:subquery"],"hints":["Find MAX where salary < overall MAX.","Subquery.","SELECT MAX(salary) FROM emp WHERE salary < (SELECT MAX(salary) FROM emp)"]},

    # ── Aggregations ───────────────────────────────────
    {"topic":"aggregations","diff":1,"title":"Count Orders",
     "description":"Return total number of orders as total.",
     "sample_data":"CREATE TABLE orders(id INT);\nINSERT INTO orders VALUES(1),(2),(3),(4),(5);",
     "expected_output":"5",
     "solution":"SELECT COUNT(*) AS total FROM orders;",
     "tags":["sql:aggregation"],"hints":["COUNT(*).","Alias with AS.","SELECT COUNT(*) AS total FROM orders"]},
    {"topic":"aggregations","diff":1,"title":"Average Price",
     "description":"Return average price as avg_price, rounded to 2 decimals.",
     "sample_data":"CREATE TABLE products(id INT,price REAL);\nINSERT INTO products VALUES(1,10),(2,20),(3,30);",
     "expected_output":"20.0",
     "solution":"SELECT ROUND(AVG(price),2) AS avg_price FROM products;",
     "tags":["sql:aggregation"],"hints":["AVG.","ROUND(x,2).","ROUND(AVG(price),2)"]},
    {"topic":"aggregations","diff":1,"title":"Min And Max Price",
     "description":"Return min_price and max_price from products.",
     "sample_data":"CREATE TABLE products(id INT,price REAL);\nINSERT INTO products VALUES(1,5),(2,50),(3,15);",
     "expected_output":"5.0|50.0",
     "solution":"SELECT MIN(price) AS min_price, MAX(price) AS max_price FROM products;",
     "tags":["sql:aggregation"],"hints":["MIN, MAX.","One row, two columns.","SELECT MIN(price), MAX(price)"]},
    {"topic":"aggregations","diff":2,"title":"Unique Customers",
     "description":"From orders, count distinct customer_id as unique_customers.",
     "sample_data":"CREATE TABLE orders(id INT,customer_id INT);\nINSERT INTO orders VALUES(1,10),(2,11),(3,10),(4,12);",
     "expected_output":"3",
     "solution":"SELECT COUNT(DISTINCT customer_id) AS unique_customers FROM orders;",
     "tags":["sql:aggregation"],"hints":["COUNT with DISTINCT.","Inside parens.","COUNT(DISTINCT customer_id)"]},
    {"topic":"aggregations","diff":2,"title":"Total Revenue",
     "description":"Compute total revenue as revenue = sum of qty * price.",
     "sample_data":"CREATE TABLE sales(id INT,qty INT,price REAL);\nINSERT INTO sales VALUES(1,2,10),(2,3,5),(3,1,20);",
     "expected_output":"55.0",
     "solution":"SELECT SUM(qty*price) AS revenue FROM sales;",
     "tags":["sql:aggregation"],"hints":["Multiply inside SUM.","SUM(qty*price).","SELECT SUM(qty*price) AS revenue FROM sales"]},

    # ── GROUP BY + HAVING ──────────────────────────────
    {"topic":"group_by_having","diff":2,"title":"Headcount By Department",
     "description":"Return department and headcount (count of employees), ordered by department.",
     "sample_data":"CREATE TABLE emp(id INT,department TEXT);\nINSERT INTO emp VALUES(1,'Eng'),(2,'Sales'),(3,'Eng'),(4,'HR'),(5,'Eng');",
     "expected_output":"Eng|3\nHR|1\nSales|1",
     "solution":"SELECT department, COUNT(*) AS headcount FROM emp GROUP BY department ORDER BY department;",
     "tags":["sql:group_by"],"hints":["GROUP BY department.","COUNT(*).","GROUP BY department"]},
    {"topic":"group_by_having","diff":2,"title":"Avg Salary By Department",
     "description":"Return department, avg_salary per department, ordered by department.",
     "sample_data":"CREATE TABLE emp(id INT,department TEXT,salary INT);\nINSERT INTO emp VALUES(1,'Eng',100),(2,'Eng',120),(3,'Sales',80),(4,'Sales',90);",
     "expected_output":"Eng|110.0\nSales|85.0",
     "solution":"SELECT department, AVG(salary) AS avg_salary FROM emp GROUP BY department ORDER BY department;",
     "tags":["sql:group_by","sql:aggregation"],"hints":["AVG(salary) + GROUP BY.","One row per dept.","GROUP BY department"]},
    {"topic":"group_by_having","diff":3,"title":"Departments With 3+ Employees",
     "description":"Return department of teams with at least 3 employees.",
     "sample_data":"CREATE TABLE emp(id INT,department TEXT);\nINSERT INTO emp VALUES(1,'Eng'),(2,'Eng'),(3,'Eng'),(4,'Sales'),(5,'HR'),(6,'HR');",
     "expected_output":"Eng",
     "solution":"SELECT department FROM emp GROUP BY department HAVING COUNT(*) >= 3 ORDER BY department;",
     "tags":["sql:group_by","sql:having"],"hints":["HAVING filters groups.","COUNT(*) >= 3.","HAVING COUNT(*) >= 3"]},
    {"topic":"group_by_having","diff":3,"title":"High Earning Departments",
     "description":"Return department where average salary > 90.",
     "sample_data":"CREATE TABLE emp(id INT,department TEXT,salary INT);\nINSERT INTO emp VALUES(1,'Eng',100),(2,'Eng',120),(3,'Sales',80),(4,'HR',95);",
     "expected_output":"Eng\nHR",
     "solution":"SELECT department FROM emp GROUP BY department HAVING AVG(salary) > 90 ORDER BY department;",
     "tags":["sql:group_by","sql:having"],"hints":["HAVING uses aggregates.","AVG(salary) > 90.","HAVING AVG(salary) > 90"]},
    {"topic":"group_by_having","diff":3,"title":"Revenue Per Product",
     "description":"For each product_id, return revenue = SUM(qty*price). Order by revenue desc.",
     "sample_data":"CREATE TABLE sales(product_id INT,qty INT,price REAL);\nINSERT INTO sales VALUES(1,2,10),(2,1,50),(1,3,10),(2,2,50);",
     "expected_output":"2|150.0\n1|50.0",
     "solution":"SELECT product_id, SUM(qty*price) AS revenue FROM sales GROUP BY product_id ORDER BY revenue DESC;",
     "tags":["sql:group_by","sql:aggregation"],"hints":["GROUP BY product_id.","SUM(qty*price).","ORDER BY revenue DESC"]},
    {"topic":"group_by_having","diff":3,"title":"Orders Per Month",
     "description":"Return month (YYYY-MM) and order_count per month, sorted by month.",
     "sample_data":"CREATE TABLE orders(id INT,created_at TEXT);\nINSERT INTO orders VALUES(1,'2024-01-05'),(2,'2024-01-20'),(3,'2024-02-01'),(4,'2024-02-10'),(5,'2024-03-15');",
     "expected_output":"2024-01|2\n2024-02|2\n2024-03|1",
     "solution":"SELECT substr(created_at,1,7) AS month, COUNT(*) AS order_count FROM orders GROUP BY month ORDER BY month;",
     "tags":["sql:group_by","sql:date_functions"],"hints":["Extract YYYY-MM with substr.","GROUP BY that expression.","substr(created_at,1,7)"]},

    # ── JOINs ──────────────────────────────────────────
    {"topic":"joins","diff":2,"title":"Order With Customer Name",
     "description":"Return o.id, c.name, o.amount joining orders to customers, ordered by o.id.",
     "sample_data":"CREATE TABLE customers(id INT,name TEXT);\nINSERT INTO customers VALUES(1,'Alice'),(2,'Bob'),(3,'Carol');\nCREATE TABLE orders(id INT,customer_id INT,amount REAL);\nINSERT INTO orders VALUES(10,1,100),(11,1,50),(12,2,200);",
     "expected_output":"10|Alice|100.0\n11|Alice|50.0\n12|Bob|200.0",
     "solution":"SELECT o.id, c.name, o.amount FROM orders o JOIN customers c ON c.id = o.customer_id ORDER BY o.id;",
     "tags":["sql:joins"],"hints":["INNER JOIN.","ON c.id = o.customer_id.","JOIN customers c ON c.id = o.customer_id"]},
    {"topic":"joins","diff":2,"title":"Customers Without Orders",
     "description":"Return name of customers with zero orders.",
     "sample_data":"CREATE TABLE customers(id INT,name TEXT);\nINSERT INTO customers VALUES(1,'Alice'),(2,'Bob'),(3,'Carol');\nCREATE TABLE orders(id INT,customer_id INT,amount REAL);\nINSERT INTO orders VALUES(10,1,100),(11,1,50),(12,2,200);",
     "expected_output":"Carol",
     "solution":"SELECT c.name FROM customers c LEFT JOIN orders o ON o.customer_id = c.id WHERE o.id IS NULL ORDER BY c.name;",
     "tags":["sql:joins"],"hints":["LEFT JOIN.","Unmatched rows become NULL.","WHERE o.id IS NULL"]},
    {"topic":"joins","diff":3,"title":"Total Spend Per Customer",
     "description":"Return name, total_spend for every customer (NULL becomes 0), ordered by name.",
     "sample_data":"CREATE TABLE customers(id INT,name TEXT);\nINSERT INTO customers VALUES(1,'Alice'),(2,'Bob'),(3,'Carol');\nCREATE TABLE orders(id INT,customer_id INT,amount REAL);\nINSERT INTO orders VALUES(10,1,100),(11,1,50),(12,2,200);",
     "expected_output":"Alice|150.0\nBob|200.0\nCarol|0",
     "solution":"SELECT c.name, COALESCE(SUM(o.amount),0) AS total_spend FROM customers c LEFT JOIN orders o ON o.customer_id=c.id GROUP BY c.id, c.name ORDER BY c.name;",
     "tags":["sql:joins","sql:aggregation"],"hints":["LEFT JOIN keeps all customers.","COALESCE for NULL totals.","GROUP BY c.id, c.name"]},
    {"topic":"joins","diff":3,"title":"Employees And Their Managers",
     "description":"Return employee_name, manager_name for every employee. If no manager, show NULL.",
     "sample_data":"CREATE TABLE emp(id INT,name TEXT,manager_id INT);\nINSERT INTO emp VALUES(1,'Alice',NULL),(2,'Bob',1),(3,'Carol',1),(4,'Dan',2);",
     "expected_output":"Alice|None\nBob|Alice\nCarol|Alice\nDan|Bob",
     "solution":"SELECT e.name AS employee_name, m.name AS manager_name FROM emp e LEFT JOIN emp m ON m.id = e.manager_id ORDER BY e.id;",
     "tags":["sql:joins","sql:advanced_joins"],"hints":["Self-join: alias the same table twice.","LEFT JOIN for nullable manager.","LEFT JOIN emp m ON m.id = e.manager_id"]},
    {"topic":"joins","diff":3,"title":"Three Table Join",
     "description":"Return customer_name, product_name, qty joining orders to customers and products. Sort by customer_name, product_name.",
     "sample_data":"CREATE TABLE customers(id INT,name TEXT);\nINSERT INTO customers VALUES(1,'Alice'),(2,'Bob');\nCREATE TABLE products(id INT,name TEXT);\nINSERT INTO products VALUES(10,'Pen'),(11,'Mug');\nCREATE TABLE orders(id INT,customer_id INT,product_id INT,qty INT);\nINSERT INTO orders VALUES(1,1,10,2),(2,1,11,1),(3,2,10,3);",
     "expected_output":"Alice|Mug|1\nAlice|Pen|2\nBob|Pen|3",
     "solution":"SELECT c.name AS customer_name, p.name AS product_name, o.qty FROM orders o JOIN customers c ON c.id=o.customer_id JOIN products p ON p.id=o.product_id ORDER BY c.name, p.name;",
     "tags":["sql:joins"],"hints":["Chain two JOINs.","One JOIN per FK.","JOIN customers c ON ... JOIN products p ON ..."]},
    {"topic":"joins","diff":3,"title":"Products Never Sold",
     "description":"Return name of products with no rows in sales.",
     "sample_data":"CREATE TABLE products(id INT,name TEXT);\nINSERT INTO products VALUES(1,'A'),(2,'B'),(3,'C');\nCREATE TABLE sales(id INT,product_id INT);\nINSERT INTO sales VALUES(1,1),(2,1),(3,3);",
     "expected_output":"B",
     "solution":"SELECT p.name FROM products p LEFT JOIN sales s ON s.product_id=p.id WHERE s.id IS NULL ORDER BY p.name;",
     "tags":["sql:joins"],"hints":["LEFT JOIN + IS NULL.","Anti-join pattern.","WHERE s.id IS NULL"]},
    {"topic":"joins","diff":3,"title":"Cartesian Pairing",
     "description":"Given sizes(s) and colors(c), return every (s,c) pair ordered by size then color.",
     "sample_data":"CREATE TABLE sizes(s TEXT);\nINSERT INTO sizes VALUES('S'),('M'),('L');\nCREATE TABLE colors(c TEXT);\nINSERT INTO colors VALUES('red'),('blue');",
     "expected_output":"L|blue\nL|red\nM|blue\nM|red\nS|blue\nS|red",
     "solution":"SELECT s.s AS size, c.c AS color FROM sizes s CROSS JOIN colors c ORDER BY s.s, c.c;",
     "tags":["sql:joins","sql:advanced_joins"],"hints":["CROSS JOIN = every combination.","No ON clause.","CROSS JOIN"]},
    {"topic":"joins","diff":3,"title":"Customers Who Bought Product 10",
     "description":"Return distinct name of customers who ever bought product_id=10.",
     "sample_data":"CREATE TABLE customers(id INT,name TEXT);\nINSERT INTO customers VALUES(1,'A'),(2,'B'),(3,'C');\nCREATE TABLE orders(id INT,customer_id INT,product_id INT);\nINSERT INTO orders VALUES(1,1,10),(2,2,11),(3,3,10),(4,1,10);",
     "expected_output":"A\nC",
     "solution":"SELECT DISTINCT c.name FROM customers c WHERE EXISTS(SELECT 1 FROM orders o WHERE o.customer_id=c.id AND o.product_id=10) ORDER BY c.name;",
     "tags":["sql:joins","sql:subquery"],"hints":["EXISTS or IN subquery.","DISTINCT to dedupe.","WHERE EXISTS (SELECT 1 FROM orders ...)"]},

    # ── Subqueries & CTEs ──────────────────────────────
    {"topic":"subqueries_ctes","diff":3,"title":"Above-Average Salary",
     "description":"Return name of employees earning above the overall average salary.",
     "sample_data":"CREATE TABLE emp(id INT,name TEXT,salary INT);\nINSERT INTO emp VALUES(1,'A',50),(2,'B',100),(3,'C',150),(4,'D',80);",
     "expected_output":"B\nC",
     "solution":"SELECT name FROM emp WHERE salary > (SELECT AVG(salary) FROM emp) ORDER BY name;",
     "tags":["sql:subquery"],"hints":["Scalar subquery.","Average = 95.","salary > (SELECT AVG(salary) FROM emp)"]},
    {"topic":"subqueries_ctes","diff":3,"title":"CTE High Spenders",
     "description":"Using a CTE, find customers with total order amount > 100. Return customer_id, total.",
     "sample_data":"CREATE TABLE orders(id INT,customer_id INT,amount REAL);\nINSERT INTO orders VALUES(1,1,50),(2,1,80),(3,2,40),(4,3,200);",
     "expected_output":"1|130.0\n3|200.0",
     "solution":"WITH totals AS (SELECT customer_id, SUM(amount) AS total FROM orders GROUP BY customer_id)\nSELECT customer_id, total FROM totals WHERE total > 100 ORDER BY customer_id;",
     "tags":["sql:cte"],"hints":["WITH ... AS (...).","Filter the CTE.","WHERE total > 100"]},
    {"topic":"subqueries_ctes","diff":3,"title":"Highest Paid Per Department",
     "description":"Return name, department, salary of the highest-paid employee in each department.",
     "sample_data":"CREATE TABLE emp(id INT,name TEXT,department TEXT,salary INT);\nINSERT INTO emp VALUES(1,'A','Eng',100),(2,'B','Eng',120),(3,'C','Sales',80),(4,'D','Sales',90);",
     "expected_output":"B|Eng|120\nD|Sales|90",
     "solution":"SELECT name, department, salary FROM emp e WHERE salary = (SELECT MAX(salary) FROM emp WHERE department = e.department) ORDER BY department;",
     "tags":["sql:subquery"],"hints":["Correlated subquery refs outer row.","WHERE department = e.department.","= (SELECT MAX(salary) FROM emp WHERE department = e.department)"]},
    {"topic":"subqueries_ctes","diff":3,"title":"Users With No Orders NOT IN",
     "description":"Return id, name of users with no orders, using NOT IN.",
     "sample_data":"CREATE TABLE users(id INT,name TEXT);\nINSERT INTO users VALUES(1,'A'),(2,'B'),(3,'C');\nCREATE TABLE orders(id INT,user_id INT);\nINSERT INTO orders VALUES(1,1),(2,1),(3,3);",
     "expected_output":"2|B",
     "solution":"SELECT id, name FROM users WHERE id NOT IN (SELECT user_id FROM orders WHERE user_id IS NOT NULL) ORDER BY id;",
     "tags":["sql:subquery"],"hints":["Subquery returns a column.","Beware NULLs in NOT IN.","WHERE user_id IS NOT NULL"]},
    {"topic":"subqueries_ctes","diff":3,"title":"Two-Step CTE Pipeline",
     "description":"Step 1: per-customer totals. Step 2: return top 2 by total (customer_id, total).",
     "sample_data":"CREATE TABLE orders(id INT,customer_id INT,amount REAL);\nINSERT INTO orders VALUES(1,1,50),(2,2,200),(3,3,150),(4,1,80),(5,2,30);",
     "expected_output":"2|230.0\n3|150.0",
     "solution":"WITH totals AS (SELECT customer_id, SUM(amount) AS total FROM orders GROUP BY customer_id)\nSELECT customer_id, total FROM totals ORDER BY total DESC LIMIT 2;",
     "tags":["sql:cte"],"hints":["CTE then ORDER BY.","LIMIT 2.","ORDER BY total DESC LIMIT 2"]},
    {"topic":"subqueries_ctes","diff":4,"title":"Recursive Numbers 1 to 5",
     "description":"Using a recursive CTE, return numbers 1 through 5 as column n.",
     "sample_data":"CREATE TABLE dummy(x INT); INSERT INTO dummy VALUES(0);",
     "expected_output":"1\n2\n3\n4\n5",
     "solution":"WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM seq WHERE n<5) SELECT n FROM seq ORDER BY n;",
     "tags":["sql:recursive_cte","sql:cte"],"hints":["WITH RECURSIVE.","Anchor UNION ALL recursive step.","WHERE n<5 stops recursion"]},

    # ── Window Functions ───────────────────────────────
    {"topic":"window_functions","diff":3,"title":"ROW_NUMBER By Salary",
     "description":"Return name, salary, rn where rn is the row number ordered by salary DESC.",
     "sample_data":"CREATE TABLE emp(id INT,name TEXT,salary INT);\nINSERT INTO emp VALUES(1,'A',100),(2,'B',120),(3,'C',90),(4,'D',80),(5,'E',95);",
     "expected_output":"B|120|1\nA|100|2\nE|95|3\nC|90|4\nD|80|5",
     "solution":"SELECT name, salary, ROW_NUMBER() OVER (ORDER BY salary DESC) AS rn FROM emp ORDER BY rn;",
     "tags":["sql:window_functions"],"hints":["ROW_NUMBER() OVER (...).","ORDER BY salary DESC.","ROW_NUMBER() OVER (ORDER BY salary DESC)"]},
    {"topic":"window_functions","diff":3,"title":"DENSE_RANK Over Salary",
     "description":"Return salary, rk where rk = DENSE_RANK over salary DESC. Same salary = same rank.",
     "sample_data":"CREATE TABLE emp(id INT,salary INT);\nINSERT INTO emp VALUES(1,100),(2,100),(3,90),(4,80);",
     "expected_output":"100|1\n100|1\n90|2\n80|3",
     "solution":"SELECT salary, DENSE_RANK() OVER (ORDER BY salary DESC) AS rk FROM emp ORDER BY salary DESC, rk;",
     "tags":["sql:window_functions"],"hints":["DENSE_RANK skips no values for ties.","Same salary = same rank.","DENSE_RANK() OVER (ORDER BY salary DESC)"]},
    {"topic":"window_functions","diff":3,"title":"Top Per Department",
     "description":"Return name, department, salary of the top earner in each department using ROW_NUMBER.",
     "sample_data":"CREATE TABLE emp(id INT,name TEXT,department TEXT,salary INT);\nINSERT INTO emp VALUES(1,'A','Eng',100),(2,'B','Eng',120),(3,'C','Eng',90),(4,'D','Sales',80),(5,'E','Sales',95);",
     "expected_output":"B|Eng|120\nE|Sales|95",
     "solution":"WITH r AS (SELECT name, department, salary, ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS rn FROM emp)\nSELECT name, department, salary FROM r WHERE rn=1 ORDER BY department;",
     "tags":["sql:window_functions"],"hints":["PARTITION BY department.","Pick rn=1.","ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC)"]},
    {"topic":"window_functions","diff":3,"title":"Previous Day Price LAG",
     "description":"For each day, return day, price, prev_price using LAG ordered by day.",
     "sample_data":"CREATE TABLE prices(day INT,price REAL);\nINSERT INTO prices VALUES(1,100),(2,105),(3,103),(4,110);",
     "expected_output":"1|100.0|None\n2|105.0|100.0\n3|103.0|105.0\n4|110.0|103.0",
     "solution":"SELECT day, price, LAG(price) OVER (ORDER BY day) AS prev_price FROM prices ORDER BY day;",
     "tags":["sql:window_functions","sql:lag_lead"],"hints":["LAG() OVER (ORDER BY day).","First row is NULL.","LAG(price) OVER (ORDER BY day)"]},
    {"topic":"window_functions","diff":3,"title":"Running Total",
     "description":"Return day, amount, running_total (cumulative sum ordered by day).",
     "sample_data":"CREATE TABLE sales(day INT,amount REAL);\nINSERT INTO sales VALUES(1,10),(2,20),(3,5),(4,15);",
     "expected_output":"1|10.0|10.0\n2|20.0|30.0\n3|5.0|35.0\n4|15.0|50.0",
     "solution":"SELECT day, amount, SUM(amount) OVER (ORDER BY day ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total FROM sales ORDER BY day;",
     "tags":["sql:window_functions"],"hints":["SUM() OVER with ORDER BY.","Frame: UNBOUNDED PRECEDING.","SUM(amount) OVER (ORDER BY day)"]},
    {"topic":"window_functions","diff":3,"title":"Share Of Department Salary",
     "description":"Return name, department, share where share = ROUND(salary*1.0 / SUM(salary) OVER (PARTITION BY department), 2).",
     "sample_data":"CREATE TABLE emp(id INT,name TEXT,department TEXT,salary INT);\nINSERT INTO emp VALUES(1,'A','Eng',100),(2,'B','Eng',120),(3,'C','Eng',90),(4,'D','Sales',80),(5,'E','Sales',95);",
     "expected_output":"A|Eng|0.32\nB|Eng|0.39\nC|Eng|0.29\nD|Sales|0.46\nE|Sales|0.54",
     "solution":"SELECT name, department, ROUND(salary*1.0 / SUM(salary) OVER (PARTITION BY department), 2) AS share FROM emp ORDER BY department, name;",
     "tags":["sql:window_functions"],"hints":["Ratio with windowed SUM.","PARTITION BY department.","SUM(salary) OVER (PARTITION BY department)"]},
    {"topic":"window_functions","diff":4,"title":"Salary Quartiles NTILE",
     "description":"Return name, salary, q where q = NTILE(4) OVER (ORDER BY salary).",
     "sample_data":"CREATE TABLE emp(id INT,name TEXT,salary INT);\nINSERT INTO emp VALUES(1,'A',60),(2,'B',70),(3,'C',80),(4,'D',90),(5,'E',100),(6,'F',110),(7,'G',120),(8,'H',130);",
     "expected_output":"A|60|1\nB|70|1\nC|80|2\nD|90|2\nE|100|3\nF|110|3\nG|120|4\nH|130|4",
     "solution":"SELECT name, salary, NTILE(4) OVER (ORDER BY salary) AS q FROM emp ORDER BY salary;",
     "tags":["sql:window_functions"],"hints":["NTILE(n) splits rows into n buckets.","ORDER BY salary asc.","NTILE(4) OVER (ORDER BY salary)"]},
    {"topic":"window_functions","diff":3,"title":"First Login Per User",
     "description":"For each row return user_id, ts, first_ts where first_ts is FIRST_VALUE(ts) OVER (PARTITION BY user_id ORDER BY ts).",
     "sample_data":"CREATE TABLE logins(user_id INT,ts INT);\nINSERT INTO logins VALUES(1,100),(1,200),(2,150),(2,180),(1,300);",
     "expected_output":"1|100|100\n1|200|100\n1|300|100\n2|150|150\n2|180|150",
     "solution":"SELECT user_id, ts, FIRST_VALUE(ts) OVER (PARTITION BY user_id ORDER BY ts) AS first_ts FROM logins ORDER BY user_id, ts;",
     "tags":["sql:window_functions"],"hints":["FIRST_VALUE.","PARTITION BY user_id.","FIRST_VALUE(ts) OVER (PARTITION BY user_id ORDER BY ts)"]},

    # ── String / Date Functions ────────────────────────
    {"topic":"string_date_functions","diff":1,"title":"Uppercase Names",
     "description":"Return name from users in UPPERCASE as upper_name, ordered by name.",
     "sample_data":"CREATE TABLE users(id INT,name TEXT); INSERT INTO users VALUES(1,'alice'),(2,'bob'),(3,'carol');",
     "expected_output":"ALICE\nBOB\nCAROL",
     "solution":"SELECT UPPER(name) AS upper_name FROM users ORDER BY name;",
     "tags":["sql:date_functions"],"hints":["UPPER().","Order by original name.","SELECT UPPER(name) AS upper_name"]},
    {"topic":"string_date_functions","diff":2,"title":"Full Name Concat",
     "description":"Concatenate first_name || ' ' || last_name as full_name. Order by full_name.",
     "sample_data":"CREATE TABLE users(id INT,first_name TEXT,last_name TEXT); INSERT INTO users VALUES(1,'Ada','Lovelace'),(2,'Alan','Turing');",
     "expected_output":"Ada Lovelace\nAlan Turing",
     "solution":"SELECT first_name || ' ' || last_name AS full_name FROM users ORDER BY full_name;",
     "tags":["sql:date_functions"],"hints":["SQLite uses ||.","Quote space carefully.","first_name || ' ' || last_name"]},
    {"topic":"string_date_functions","diff":2,"title":"Short Usernames",
     "description":"Return name where LENGTH(name) <= 4. Order by name.",
     "sample_data":"CREATE TABLE u(id INT,name TEXT); INSERT INTO u VALUES(1,'Ann'),(2,'Bobby'),(3,'Cal'),(4,'Dwight');",
     "expected_output":"Ann\nCal",
     "solution":"SELECT name FROM u WHERE LENGTH(name) <= 4 ORDER BY name;",
     "tags":["sql:date_functions"],"hints":["LENGTH() returns chars.","Compare with <=.","WHERE LENGTH(name) <= 4"]},
    {"topic":"string_date_functions","diff":3,"title":"Orders In 2024",
     "description":"Return id of orders where year of created_at is 2024.",
     "sample_data":"CREATE TABLE orders(id INT,created_at TEXT);\nINSERT INTO orders VALUES(1,'2023-12-01'),(2,'2024-01-15'),(3,'2024-07-20'),(4,'2025-01-01');",
     "expected_output":"2\n3",
     "solution":"SELECT id FROM orders WHERE substr(created_at,1,4) = '2024' ORDER BY id;",
     "tags":["sql:date_functions"],"hints":["substr(date,1,4) = year.","Compare to '2024'.","WHERE substr(created_at,1,4)='2024'"]},
    {"topic":"string_date_functions","diff":3,"title":"Days Between Events",
     "description":"Return id, days where days = julianday(end_date) - julianday(start_date) as integer.",
     "sample_data":"CREATE TABLE events(id INT,start_date TEXT,end_date TEXT);\nINSERT INTO events VALUES(1,'2024-01-01','2024-01-10'),(2,'2024-02-01','2024-02-05');",
     "expected_output":"1|9\n2|4",
     "solution":"SELECT id, CAST(julianday(end_date) - julianday(start_date) AS INT) AS days FROM events ORDER BY id;",
     "tags":["sql:date_functions"],"hints":["julianday() to numeric.","CAST to INT.","julianday(end_date) - julianday(start_date)"]},

    # ── CASE WHEN ──────────────────────────────────────
    {"topic":"case_when","diff":2,"title":"Salary Buckets",
     "description":"Return name, bucket where bucket = low if salary<80, mid if <120, else high. Order by name.",
     "sample_data":"CREATE TABLE emp(id INT,name TEXT,salary INT);\nINSERT INTO emp VALUES(1,'A',60),(2,'B',100),(3,'C',150),(4,'D',80);",
     "expected_output":"A|low\nB|mid\nC|high\nD|mid",
     "solution":"SELECT name, CASE WHEN salary < 80 THEN 'low' WHEN salary < 120 THEN 'mid' ELSE 'high' END AS bucket FROM emp ORDER BY name;",
     "tags":["sql:case_when"],"hints":["CASE WHEN ... THEN ... ELSE ... END.","Conditions checked in order.","CASE WHEN salary<80 THEN 'low' ..."]},
    {"topic":"case_when","diff":2,"title":"Email Or Fallback",
     "description":"Return id, email_or_unknown where missing emails show unknown.",
     "sample_data":"CREATE TABLE u(id INT,email TEXT); INSERT INTO u VALUES(1,'a@x.com'),(2,NULL),(3,'c@x.com');",
     "expected_output":"1|a@x.com\n2|unknown\n3|c@x.com",
     "solution":"SELECT id, COALESCE(email,'unknown') AS email_or_unknown FROM u ORDER BY id;",
     "tags":["sql:case_when","sql:null_semantics"],"hints":["COALESCE is cleaner than CASE here.","Same as CASE WHEN email IS NULL.","COALESCE(email,'unknown')"]},
    {"topic":"case_when","diff":3,"title":"Conditional Counting",
     "description":"Return paid_count and cancelled_count as a single row using SUM(CASE...).",
     "sample_data":"CREATE TABLE orders(id INT,status TEXT);\nINSERT INTO orders VALUES(1,'paid'),(2,'cancelled'),(3,'paid'),(4,'pending'),(5,'paid');",
     "expected_output":"3|1",
     "solution":"SELECT SUM(CASE WHEN status='paid' THEN 1 ELSE 0 END) AS paid_count, SUM(CASE WHEN status='cancelled' THEN 1 ELSE 0 END) AS cancelled_count FROM orders;",
     "tags":["sql:case_when","sql:aggregation"],"hints":["Pivot-style aggregation.","SUM(CASE...).","SUM(CASE WHEN status='paid' THEN 1 ELSE 0 END)"]},
    {"topic":"case_when","diff":3,"title":"Pivot Status By Day",
     "description":"For each day, return day, paid, cancelled counts sorted by day.",
     "sample_data":"CREATE TABLE orders(id INT,day INT,status TEXT);\nINSERT INTO orders VALUES(1,1,'paid'),(2,1,'cancelled'),(3,2,'paid'),(4,2,'paid'),(5,3,'cancelled');",
     "expected_output":"1|1|1\n2|2|0\n3|0|1",
     "solution":"SELECT day, SUM(CASE WHEN status='paid' THEN 1 ELSE 0 END) AS paid, SUM(CASE WHEN status='cancelled' THEN 1 ELSE 0 END) AS cancelled FROM orders GROUP BY day ORDER BY day;",
     "tags":["sql:case_when","sql:group_by"],"hints":["GROUP BY day.","CASE inside SUM.","SUM(CASE WHEN status='paid' THEN 1 ELSE 0 END)"]},

    # ── Set Operations ─────────────────────────────────
    {"topic":"set_operations","diff":2,"title":"UNION Two Sources",
     "description":"Return distinct emails from both web_users and app_users sorted A-Z.",
     "sample_data":"CREATE TABLE web_users(email TEXT); INSERT INTO web_users VALUES('a@x.com'),('b@x.com');\nCREATE TABLE app_users(email TEXT); INSERT INTO app_users VALUES('b@x.com'),('c@x.com');",
     "expected_output":"a@x.com\nb@x.com\nc@x.com",
     "solution":"SELECT email FROM web_users UNION SELECT email FROM app_users ORDER BY email;",
     "tags":["sql:set_operations"],"hints":["UNION dedupes; UNION ALL doesn't.","Sort at the end.","UNION ... ORDER BY email"]},
    {"topic":"set_operations","diff":3,"title":"Web-Only Emails EXCEPT",
     "description":"Return emails in web_users but NOT in app_users, sorted.",
     "sample_data":"CREATE TABLE web_users(email TEXT); INSERT INTO web_users VALUES('a@x.com'),('b@x.com'),('d@x.com');\nCREATE TABLE app_users(email TEXT); INSERT INTO app_users VALUES('b@x.com'),('c@x.com');",
     "expected_output":"a@x.com\nd@x.com",
     "solution":"SELECT email FROM web_users EXCEPT SELECT email FROM app_users ORDER BY email;",
     "tags":["sql:set_operations"],"hints":["EXCEPT = difference.","Both queries same shape.","EXCEPT then ORDER BY"]},

    # ── Scenario / Pipeline ────────────────────────────
    {"topic":"scenario_pipeline","diff":3,"title":"Top 2 Salaries Per Department",
     "description":"Return department, name, salary for the top 2 earners in each department.",
     "sample_data":"CREATE TABLE emp(id INT,name TEXT,department TEXT,salary INT);\nINSERT INTO emp VALUES(1,'A','Eng',100),(2,'B','Eng',120),(3,'C','Eng',90),(4,'D','Sales',80),(5,'E','Sales',95);",
     "expected_output":"Eng|B|120\nEng|A|100\nSales|E|95\nSales|D|80",
     "solution":"WITH r AS (SELECT department, name, salary, ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC, name) AS rn FROM emp) SELECT department, name, salary FROM r WHERE rn<=2 ORDER BY department, rn;",
     "tags":["sql:window_functions","sql:complex_analytics"],"hints":["Window with PARTITION BY.","Filter rn<=2.","ROW_NUMBER() PARTITION BY department"]},
    {"topic":"scenario_pipeline","diff":3,"title":"Deduplicate Keep Latest",
     "description":"Given events with possible duplicates (same user_id), return one row per user with the largest ts. Columns: user_id, ts, payload.",
     "sample_data":"CREATE TABLE events(user_id INT,ts INT,payload TEXT);\nINSERT INTO events VALUES(1,100,'a'),(1,200,'b'),(2,150,'c'),(2,180,'d'),(3,50,'e');",
     "expected_output":"1|200|b\n2|180|d\n3|50|e",
     "solution":"WITH r AS (SELECT user_id, ts, payload, ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY ts DESC) AS rn FROM events) SELECT user_id, ts, payload FROM r WHERE rn=1 ORDER BY user_id;",
     "tags":["sql:window_functions","sql:complex_analytics"],"hints":["Partition + row_number.","ORDER BY ts DESC.","WHERE rn=1"]},
    {"topic":"scenario_pipeline","diff":4,"title":"Funnel View Add Buy",
     "description":"Given events(user_id, step) with step in view/add/buy, return per-step user count: step, users. Sort in funnel order.",
     "sample_data":"CREATE TABLE events(user_id INT,step TEXT);\nINSERT INTO events VALUES(1,'view'),(2,'view'),(3,'view'),(1,'add'),(2,'add'),(1,'buy');",
     "expected_output":"view|3\nadd|2\nbuy|1",
     "solution":"SELECT step, COUNT(DISTINCT user_id) AS users FROM events GROUP BY step ORDER BY CASE step WHEN 'view' THEN 1 WHEN 'add' THEN 2 WHEN 'buy' THEN 3 END;",
     "tags":["sql:complex_analytics","sql:case_when"],"hints":["GROUP BY step.","COUNT DISTINCT user_id.","CASE in ORDER BY for funnel order"]},
    {"topic":"scenario_pipeline","diff":4,"title":"Consecutive Login Streak",
     "description":"For user 1, find the longest run of consecutive day values in logins. Return the streak length.",
     "sample_data":"CREATE TABLE logins(user_id INT,day INT);\nINSERT INTO logins VALUES(1,1),(1,2),(1,3),(1,5),(1,6),(1,8);",
     "expected_output":"3",
     "solution":"WITH g AS (SELECT day, day - ROW_NUMBER() OVER (ORDER BY day) AS grp FROM logins WHERE user_id=1) SELECT MAX(c) AS streak FROM (SELECT grp, COUNT(*) AS c FROM g GROUP BY grp);",
     "tags":["sql:window_functions","sql:complex_analytics"],"hints":["Trick: day - ROW_NUMBER() is constant in a run.","Group by that.","Then MAX(COUNT)"]},
    {"topic":"scenario_pipeline","diff":4,"title":"Sessionize Events 30min Gap",
     "description":"Mark each event with a session_id (per user), incrementing when gap to prev event > 30. Return user_id, ts, session_id.",
     "sample_data":"CREATE TABLE events(user_id INT,ts INT);\nINSERT INTO events VALUES(1,0),(1,10),(1,50),(1,120),(2,0),(2,5);",
     "expected_output":"1|0|1\n1|10|1\n1|50|2\n1|120|3\n2|0|1\n2|5|1",
     "solution":"WITH g AS (SELECT user_id, ts, CASE WHEN ts - LAG(ts) OVER (PARTITION BY user_id ORDER BY ts) > 30 THEN 1 ELSE 0 END AS new_sess FROM events) SELECT user_id, ts, SUM(new_sess) OVER (PARTITION BY user_id ORDER BY ts ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) + 1 AS session_id FROM g ORDER BY user_id, ts;",
     "tags":["sql:window_functions","sql:lag_lead","sql:complex_analytics"],"hints":["LAG to find gap.","Flag where gap > threshold.","Cumulative SUM of flags = session id"]},
]
